// admin/src/pages/Auth/Login.vue


<script setup>
  import { ref, onMounted } from "vue";
  import { toast } from "vue3-toastify";
  import authAPI from '../../services/NodeAPI/authAPI';
  const email = ref('');
  const password = ref('');
  const handleLogin = async() => {
    console.log(email.value);
    console.log(password.value);
    let result = await authAPI.login(email.value, password.value);
        console.log(result);
        if(!result) {
            
          return toast.error('Email hoặc mật khẩu không hợp lệ 😔 !')
        }
        // let accessTokenTemp = Cookies.get("accessToken");
        // console.log(accessTokenTemp);
        // await dispatch(fetchUserData());
        if(result == "403"){
          return toast.error('Tài khoản không có quyền truy cập 😊 !')
        }
        window.location.href = '/';
        return toast.success('Đăng nhập thành công 😊 !')
  }

    

</script>
<style >
    @import './auth.css';
</style>
<template>
    <div class='auth'>
            <div class="row justify-content-center">
                <div class="col-xl-6 col-lg-8 ">
                    <div class='login box-auth'>

                        <div class="title-top text-center">
                            <h2>
                                Đăng nhập vào Bonik.
                            </h2>
                            <!-- <div class="action-to-register mt-2">
                                <span>
                                    Don’t have an account?
                                </span>
                                <router-link to="" class='ms-1'>
                                    Create a free account
                                </router-link>
                            </div> -->
                        </div>
                        <div class="login-social mt-5 row">
                            <div class="col-4">
                                <div class="option-item">
                                    <img src="https://shofy-angular.vercel.app/assets/img/icon/login/google.svg" alt="" />
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="option-item">
                                    <img src="https://shofy-angular.vercel.app/assets/img/icon/login/facebook.svg" alt="" />
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="option-item">
                                    <img src="https://shofy-angular.vercel.app/assets/img/icon/login/apple.svg" alt="" />
                                </div>
                            </div>

                        </div>

                        <!-- <div class="text-center-auth mt-5 row align-items-center">
                            <hr class='col-2 col-md-3 col-lg-4' />
                            <p class='col-8 col-md-6 col-lg-4 text-center'>
                                or Sign in with Email
                            </p>
                            <hr class='col-2 col-md-3 col-lg-4'/>
                        </div> -->

                        <div class="form-input mt-5">
                            <div class="input w-100">
                              <v-text-field
                                label="Email"
                                outlined
                                placeholder="Nhập email của bạn"
                                v-model="email"
                              ></v-text-field>
                                <!-- onChange={(e)=>{setEmail(e.target.value)}}  -->
                            </div>
                            <div class="input mt-4 w-100">
                              <v-text-field
                                label="Mật khẩu"
                                filled
                                placeholder="Nhập email của bạn"
                                type="password"
                                v-model="password"
                              ></v-text-field>
                                <!-- onChange={(e)=>{setPass(e.target.value)}}  -->
                            </div>
                            <div class="btn-submit mt-4">
                                <button @click="handleLogin()" class='btn rounded-0'>
                                    Đăng nhập
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</template>

// client/src/pages/auth/Login.jsx
import React, { useState } from 'react';

import { Link, useNavigate } from 'react-router-dom';

import './Styles.css';
import { TextField } from '@mui/material';
import toast from 'react-hot-toast';
import isValidEmail from '../../../util/isValidEmail';
import AuthAPI from '../../service/NodejsServerAPI/AuthAPI';
import Cookies from 'js-cookie';
import { useDispatch } from 'react-redux';
import { fetchUserData } from '../../redux/actions/userAction';

const Login = () => {
    // Lấy giá trị của tham số 'redirect' từ query string
    const queryString = window.location.search;
    const urlParams = new URLSearchParams(queryString);
    const redirectParam = urlParams.get('redirect');
    const dispatch = useDispatch();

    // Giải mã giá trị redirect nếu có
    const decodedRedirect = redirectParam ? decodeURIComponent(redirectParam) : '/';

    const [email,setEmail] = useState();
    const [pass,setPass] = useState();
    const navigate = useNavigate();

    const handleSubmit = async () => {
        console.log(email);
        console.log(pass);
        if(!email || !pass) return toast.error('Vui lòng nhập đầy đủ dữ liệu 😔 !')
        if(!isValidEmail(email)) return toast.error('Email không hợp lệ 😔 !')
        const data = {
            email : email,
            pass : pass
        }
        const result = await AuthAPI.login(data);
        if(result) {
            // let accessTokenTemp = Cookies.get("accessToken");
            // console.log(accessTokenTemp);
            // await dispatch(fetchUserData());
            if(redirectParam) return window.location.href = decodedRedirect;
            navigate('/')
            return toast.success('Đăng nhập thành công 😊 !')
        }
        return toast.error('Email hoặc mật khẩu không hợp lệ 😔 !')
    }
    return (
        <div className='auth'>
            <div className="row justify-content-center">
                <div className="col-xl-6 col-lg-8 ">
                    <div className='login box-auth'>

                        <div className="title-top text-center">
                            <h2>
                                Login to Bonik.
                            </h2>
                            <div className="action-to-register mt-2">
                                <span>
                                    Don’t have an account?
                                </span>
                                <Link to={'/register'} className='ms-1'>
                                    Create a free account
                                </Link>
                            </div>
                        </div>
                        <div className="login-social mt-5 row">
                            <div className="col-4">
                                <div className="option-item">
                                    <img src="https://shofy-angular.vercel.app/assets/img/icon/login/google.svg" alt="" />
                                </div>
                            </div>
                            <div className="col-4">
                                <div className="option-item">
                                    <img src="https://shofy-angular.vercel.app/assets/img/icon/login/facebook.svg" alt="" />
                                </div>
                            </div>
                            <div className="col-4">
                                <div className="option-item">
                                    <img src="https://shofy-angular.vercel.app/assets/img/icon/login/apple.svg" alt="" />
                                </div>
                            </div>

                        </div>

                        <div className="text-center-auth mt-5 row align-items-center">
                            <hr className='col-2 col-md-3 col-lg-4' />
                            <p className='col-8 col-md-6 col-lg-4 text-center'>
                                or Sign in with Email
                            </p>
                            <hr className='col-2 col-md-3 col-lg-4'/>
                        </div>

                        <div className="form-input mt-5">
                            <div className="input w-100">
                                <TextField 
                                id="outlined-basic" 
                                className='w-100'
                                label="Enter Your Email"
                                type='email' 
                                variant="outlined"
                                onChange={(e)=>{setEmail(e.target.value)}} />
                            </div>
                            <div className="input mt-4 w-100">
                                <TextField 
                                id="outlined-basic" 
                                className='w-100'
                                label="Enter Your Password" 
                                type='password' 
                                variant="outlined"
                                onChange={(e)=>{setPass(e.target.value)}} />
                            </div>
                            <div className="btn-submit mt-4">
                                <button onClick={handleSubmit} className='btn rounded-0'>
                                    Login
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Login;
